---
project:
  resources:
    - figures/*
  type: website

format:
  html:
    include-in-header: goatcounter.html
    theme: superhero

website:
  favicon: favicon.ico
  navbar:
    tools:
      - icon: house
        href: https://paddyroddy.github.io
      - icon: github
        href: https://github.com/paddyroddy/posters
  site-url: https://paddyroddy.github.io/posters
  title: Patrick J. Roddy
