---
project:
  resources:
    - figures/*
  type: website

format:
  html:
    theme: superhero

website:
  body-footer:
    <script async
    data-goatcounter="https://paddyroddy-posters.goatcounter.com/count"
    src="//gc.zgo.at/count.js"></script>
  favicon: favicon.ico
  navbar:
    tools:
      - icon: house
        href: https://paddyroddy.github.io
      - icon: github
        href: https://github.com/paddyroddy/posters
  site-url: https://paddyroddy.github.io/posters
  title: Patrick J. Roddy
